name: Push to Luarocks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: "scm"
          dependencies: |
            none-ls.nvim
          extra_luarocks_args: |
            --force
            --dev
